# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueDevices',
            new_name='Observables',
        ),
        migrations.RenameField(
            model_name='observables',
            old_name='device_id',
            new_name='observable_id',
        ),
        migrations.AlterUniqueTogether(
            name='devicesevents',
            unique_together=set([]),
        ),
        migrations.RenameField(
            model_name='devicesevents',
            old_name='device',
            new_name='observable'
        ),
        migrations.RenameModel(
            old_name='DevicesEvents',
            new_name='Events',
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set([('observable', 'time_seen')]),
        ),
        migrations.AddField(
            model_name="events",
            name="observations",
            field=jsonfield.fields.JSONField()
        ),
        
        migrations.RenameField(
            model_name='tmuxstatus',
            old_name='airodump_ng',
            new_name='sensor_status',
        ),
    ]
