# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190621_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='access_point_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='device_power',
        ),
        migrations.RemoveField(
            model_name='events',
            name='packets_captured',
        ),
        migrations.RemoveField(
            model_name='events',
            name='total_packets',
        ),
        migrations.AddField(
            model_name='events',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
