# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsettings',
            name='min_power',
            field=models.IntegerField(default=0),
        ),
    ]
