# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_boxsettings_min_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxsettings',
            name='min_power',
        ),
        migrations.AlterField(
            model_name='boxsettings',
            name='events_uploaded_until',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.DevicesEvents'),
        ),
        migrations.AlterField(
            model_name='boxsettings',
            name='tmux_status_uploaded_until',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.TmuxStatus'),
        ),
    ]
